import { useEffect, useMemo, useRef, useState } from "react";
import { IconCalendar, IconChevronLeft, IconChevronRight } from "@tabler/icons-react";

const weekdays = ["一", "二", "三", "四", "五", "六", "日"];
export const formatCalendarDate = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

function CalendarPanel({ selectedDate, reportDates = new Set(), markedDates = reportDates, onSelect }) {
  const [cursor, setCursor] = useState(() => { const date = new Date(`${selectedDate}T12:00:00`); return new Date(date.getFullYear(), date.getMonth(), 1); });
  const days = useMemo(() => { const firstDay = (cursor.getDay() + 6) % 7; const start = new Date(cursor.getFullYear(), cursor.getMonth(), 1 - firstDay); return Array.from({ length: 42 }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index)); }, [cursor]);
  const moveMonth = (offset) => setCursor((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  return <div className="team-calendar__panel"><div className="team-calendar__head"><div><IconCalendar size={16} /><strong>{cursor.getFullYear()}年{cursor.getMonth() + 1}月</strong></div><span><button aria-label="上个月" onClick={() => moveMonth(-1)} type="button"><IconChevronLeft size={16} /></button><button aria-label="下个月" onClick={() => moveMonth(1)} type="button"><IconChevronRight size={16} /></button></span></div><div className="team-calendar__weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="team-calendar__grid">{days.map((date) => { const dateKey = formatCalendarDate(date); const isCurrentMonth = date.getMonth() === cursor.getMonth(); const isSelected = dateKey === selectedDate; const marked = markedDates.has(dateKey); return <button className={`team-calendar__day${!isCurrentMonth ? " is-muted" : ""}${isSelected ? " is-selected" : ""}${marked ? " has-report" : ""}`} key={dateKey} onClick={() => { onSelect(dateKey); setCursor(new Date(date.getFullYear(), date.getMonth(), 1)); }} type="button"><span>{date.getDate()}</span>{marked && <i aria-hidden="true" />}</button>; })}</div></div>;
}

export function WorkbenchCalendar({ selectedDate, reportDates, markedDates, onSelect, ariaLabel = "日报日历" }) {
  return <aside className="team-calendar" aria-label={ariaLabel}><CalendarPanel selectedDate={selectedDate} reportDates={reportDates} markedDates={markedDates} onSelect={onSelect} /></aside>;
}

export function CalendarPicker({ value, onChange }) {
  const [open, setOpen] = useState(false); const pickerRef = useRef(null);
  useEffect(() => { const close = (event) => { if (!pickerRef.current?.contains(event.target)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const displayValue = value ? value.replaceAll("-", "/") : "选择日期";
  return <div className="calendar-picker" ref={pickerRef}><button className="calendar-picker__trigger" onClick={() => setOpen((current) => !current)} type="button"><span>{displayValue}</span><IconCalendar size={14} /></button>{open && <div className="calendar-picker__popover"><CalendarPanel selectedDate={value || formatCalendarDate(new Date())} onSelect={(date) => { onChange(date); setOpen(false); }} /></div>}</div>;
}

function TimePicker({ value, onChange }) { const [hour = "09", minute = "00"] = (value || "09:00").split(":"); const setTime = (nextHour, nextMinute) => onChange(`${nextHour}:${nextMinute}`); const hours = Array.from({ length: 24 }, (_, index) => String(index).padStart(2, "0")); const minutes = Array.from({ length: 12 }, (_, index) => String(index * 5).padStart(2, "0")); return <div className="calendar-time-picker"><div className="calendar-time-picker__column"><span>小时</span><div>{hours.map((item) => <button className={item === hour ? "is-selected" : ""} key={item} onClick={() => setTime(item, minute)} type="button">{item}</button>)}</div></div><b>:</b><div className="calendar-time-picker__column"><span>分钟</span><div>{minutes.map((item) => <button className={item === minute ? "is-selected" : ""} key={item} onClick={() => setTime(hour, item)} type="button">{item}</button>)}</div></div></div>; }

export function DateTimePicker({ value, onChange }) { const [open, setOpen] = useState(false); const pickerRef = useRef(null); const datePart = value?.slice(0, 10) || ""; const timePart = value?.slice(11, 16) || ""; const selectedDate = datePart || formatCalendarDate(new Date()); useEffect(() => { const close = (event) => { if (!pickerRef.current?.contains(event.target)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []); const updateDate = (date) => onChange(`${date}T${timePart || "09:00"}`); const updateTime = (time) => onChange(`${datePart || selectedDate}T${time}`); return <div className="calendar-picker calendar-picker--datetime" ref={pickerRef}><button aria-label="选择截止时间" className="calendar-picker__trigger" onClick={() => setOpen((current) => !current)} type="button"><span>{datePart ? `${datePart.replaceAll("-", "/")} ${timePart || "--:--"}` : "选择截止时间"}</span><IconCalendar size={14} /></button>{open && <div className="calendar-picker__popover"><CalendarPanel selectedDate={selectedDate} onSelect={updateDate} /><div className="calendar-picker__time"><TimePicker value={timePart} onChange={updateTime} /><button className="work-button work-button--primary" onClick={() => setOpen(false)} type="button">完成</button></div></div>}</div>; }
