import { randomUUID } from "node:crypto";
import { openLocalFirstDatabase } from "./db/local-first.mjs";
const PRIORITIES=["P0","P1","P2"],STATUSES=["open","completed"];
const fail=(code,message)=>Object.assign(new Error(message),{code});
const text=(v,max,code)=>{const x=String(v??"").trim();if(x.length>max)throw fail(code,"Invalid task field");return x||null;};
const dbStatus=s=>s==="completed"?"done":"planned",appStatus=s=>s==="done"?"completed":"open";
const map=row=>row&&({...row,detail:row.description,dueAt:row.due_at,status:appStatus(row.status),completed:row.status==="done",createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at,sourceType:row.source_type,sourceId:row.source_external_id,sourceUrl:row.source_url,priorityReason:JSON.parse(row.source_snapshot_json||"{}").priorityReason||null});
export function createTaskService({dbPath,now=()=>new Date()}) {
 const db=openLocalFirstDatabase(dbPath),stamp=()=>now().toISOString(),owner=id=>{if(!id)throw fail("IDENTITY_REQUIRED","请先登录钉钉账号。");return String(id);};
 const raw=(id,identity)=>db.prepare("SELECT * FROM work_items WHERE id=? AND owner_identity_id=? AND kind='task' AND status<>'cancelled'").get(String(id),owner(identity));
 const get=(id,identity)=>map(raw(id,identity));
 function list(identity,status="all"){if(status!=="all"&&!STATUSES.includes(status))throw fail("INVALID_TASK_STATUS","Invalid task status");const where=status==="all"?"":" AND status=?";return db.prepare(`SELECT * FROM work_items WHERE owner_identity_id=? AND kind='task' AND status<>'cancelled'${where} ORDER BY CASE status WHEN 'done' THEN 1 ELSE 0 END,priority,due_at,created_at DESC`).all(status==="all"?[owner(identity)]:[owner(identity),dbStatus(status)]).map(map);}
 function create(identity,input={}){const title=text(input.title,200,"INVALID_TASK_TITLE");if(!title)throw fail("INVALID_TASK_TITLE","Task title required");const priority=input.priority||"P1";if(!PRIORITIES.includes(priority))throw fail("INVALID_TASK_PRIORITY","Invalid priority");const own=owner(identity),sourceType=text(input.sourceType,80,"INVALID_TASK_SOURCE"),sourceId=text(input.sourceId,512,"INVALID_TASK_SOURCE");if(sourceType&&sourceId){const old=db.prepare("SELECT * FROM work_items WHERE owner_identity_id=? AND source_type=? AND source_external_id=?").get(own,sourceType,sourceId);if(old)return map(old);}const at=stamp(),id=input.id||randomUUID(),done=input.completed===true;db.prepare("INSERT INTO work_items(id,kind,title,description,status,priority,due_at,completed_at,owner_identity_id,source_type,source_external_id,source_url,source_snapshot_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,"task",title,text(input.detail??input.meta,1000,"INVALID_TASK_DETAIL"),done?"done":"planned",priority,input.dueAt||null,done?at:null,own,sourceType,sourceId,text(input.sourceUrl,2048,"INVALID_TASK_SOURCE"),JSON.stringify({priorityReason:text(input.priorityReason,500,"INVALID_TASK_PRIORITY_REASON")}),at,at);return get(id,own);}
 function update(id,identity,input={}){const old=raw(id,identity);if(!old)throw fail("TASK_NOT_FOUND","Task not found");const state=input.status===undefined?appStatus(old.status):input.status;if(!STATUSES.includes(state))throw fail("INVALID_TASK_STATUS","Invalid task status");const at=stamp();db.prepare("UPDATE work_items SET title=?,description=?,priority=?,due_at=?,status=?,completed_at=?,updated_at=? WHERE id=? AND owner_identity_id=?").run(input.title===undefined?old.title:text(input.title,200,"INVALID_TASK_TITLE"),input.detail===undefined?old.description:text(input.detail,1000,"INVALID_TASK_DETAIL"),input.priority||old.priority,input.dueAt===undefined?old.due_at:input.dueAt,dbStatus(state),state==="completed"?(old.completed_at||at):null,at,String(id),owner(identity));return get(id,identity);}
 function remove(id,identity){if(!db.prepare("UPDATE work_items SET status='cancelled',cancelled_at=?,updated_at=? WHERE id=? AND owner_identity_id=? AND kind='task'").run(stamp(),stamp(),String(id),owner(identity)).changes)throw fail("TASK_NOT_FOUND","Task not found");return {ok:true};}
 function listCompletions(identity,day){return db.prepare("SELECT * FROM work_items WHERE owner_identity_id=? AND kind='task' AND completed_at IS NOT NULL ORDER BY completed_at").all(owner(identity)).filter((item)=>String(item.completed_at).slice(0,10)===String(day)).map((item)=>({taskId:item.id,title:item.title,detail:item.description,completedAt:item.completed_at}));}
 function clearCompleted(identity){return {removed:db.prepare("UPDATE work_items SET status='cancelled',cancelled_at=?,updated_at=? WHERE owner_identity_id=? AND kind='task' AND status='done'").run(stamp(),stamp(),owner(identity)).changes};}
 return {list,get,create,update,remove,listCompletions,clearCompleted,close:()=>db.close()};
}
