import { randomUUID } from "node:crypto";
import { openLocalFirstDatabase } from "./db/local-first.mjs";
const error=(code,message)=>Object.assign(new Error(message),{code});
const owner=value=>{const id=String(value||"");if(!id)throw error("PRIVACY_LOCKED","请先连接钉钉账号。");return id;};
const validDate=(value,label)=>{const date=String(value??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(new Date(`${date}T00:00:00`).getTime()))throw error("INVALID_FOCUS_WEEK",`${label} must be YYYY-MM-DD`);return date;};
const localDate=date=>[date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0")].join("-");
export function weekEnd(start){const date=new Date(`${start}T00:00:00`);date.setDate(date.getDate()+6);return localDate(date);}
export function currentWeekStart(now=new Date()){const date=new Date(now.getFullYear(),now.getMonth(),now.getDate());date.setDate(date.getDate()-((date.getDay()||7)-1));return localDate(date);}
const field=(value,max,code,required=false)=>{const text=String(value??"").trim();if((required&&!text)||text.length>max)throw error(code,code==="INVALID_FOCUS_TITLE"?"标题不能为空":"Invalid focus field");return text||null;};
export function createWeeklyFocusService({dbPath,taskService}){
 const db=openLocalFirstDatabase(dbPath),select="SELECT id,period_start AS weekStart,period_end AS weekEnd,title,detail,manual_progress AS progress,next_step AS nextStep,status,created_at AS createdAt,updated_at AS updatedAt FROM goals";
 const hydrate=(identityId,row)=>{if(!row)return null;const taskIds=db.prepare("SELECT work_item_id AS id FROM goal_work_items WHERE goal_id=? ORDER BY created_at").all(row.id).map(item=>item.id),tasks=taskIds.map(id=>taskService.get(id,identityId)).filter(Boolean),completedTaskCount=tasks.filter(task=>task.status==="completed").length,taskProgress=tasks.length?Math.round(completedTaskCount/tasks.length*100):null;return {...row,taskIds,tasks,completedTaskCount,taskProgress,effectiveProgress:taskProgress??row.progress};};
 const get=(identityId,id)=>hydrate(identityId,db.prepare(`${select} WHERE id=? AND owner_identity_id=?`).get(String(id),owner(identityId)));
 const list=(identityId,week)=>{const account=owner(identityId),start=validDate(week||currentWeekStart(),"Week start");return db.prepare(`${select} WHERE owner_identity_id=? AND period_start=? ORDER BY created_at`).all(account,start).map(row=>hydrate(account,row));};
 function create(identityId,input={}){const account=owner(identityId),start=validDate(input.weekStart||currentWeekStart(),"Week start"),progress=Number(input.progress??0),status=input.status??"active";if(!Number.isInteger(progress)||progress<0||progress>100)throw error("INVALID_FOCUS_PROGRESS","Progress must be 0 到 100");if(!["active","completed"].includes(status))throw error("INVALID_FOCUS_STATUS","状态无效");const createdAt=new Date().toISOString(),item={id:randomUUID(),weekStart:start,weekEnd:weekEnd(start),title:field(input.title,200,"INVALID_FOCUS_TITLE",true),detail:field(input.detail,2000,"INVALID_FOCUS_DETAIL"),progress,nextStep:field(input.nextStep,1000,"INVALID_FOCUS_NEXT_STEP"),status,ownerIdentityId:account,createdAt,updatedAt:createdAt};db.prepare("INSERT INTO goals(id,period_type,period_start,period_end,title,detail,manual_progress,next_step,status,owner_identity_id,created_at,updated_at) VALUES(@id,'week',@weekStart,@weekEnd,@title,@detail,@progress,@nextStep,@status,@ownerIdentityId,@createdAt,@updatedAt)").run(item);return get(account,item.id);}
 function update(identityId,id,input={}){const account=owner(identityId),old=get(account,id);if(!old)throw error("FOCUS_NOT_FOUND","Focus not found");const progress=input.progress===undefined?old.progress:Number(input.progress),status=input.status??old.status;if(!Number.isInteger(progress)||progress<0||progress>100)throw error("INVALID_FOCUS_PROGRESS","Progress must be 0-100");if(!["active","completed"].includes(status))throw error("INVALID_FOCUS_STATUS","Invalid status");db.prepare("UPDATE goals SET title=?,detail=?,manual_progress=?,next_step=?,status=?,updated_at=? WHERE id=? AND owner_identity_id=?").run(input.title===undefined?old.title:field(input.title,200,"INVALID_FOCUS_TITLE",true),input.detail===undefined?old.detail:field(input.detail,2000,"INVALID_FOCUS_DETAIL"),progress,input.nextStep===undefined?old.nextStep:field(input.nextStep,1000,"INVALID_FOCUS_NEXT_STEP"),status,new Date().toISOString(),String(id),account);return get(account,id);}
 function remove(identityId,id){if(!db.prepare("DELETE FROM goals WHERE id=? AND owner_identity_id=?").run(String(id),owner(identityId)).changes)throw error("FOCUS_NOT_FOUND","Focus not found");return {ok:true};}
 function attachTask(identityId,goalId,taskId){const account=owner(identityId);if(!get(account,goalId))throw error("FOCUS_NOT_FOUND","Focus not found");if(!taskService.get(taskId,account))throw error("TASK_NOT_FOUND","任务不存在");try{db.prepare("INSERT INTO goal_work_items(goal_id,work_item_id,created_at) VALUES(?,?,?)").run(String(goalId),String(taskId),new Date().toISOString());}catch(failure){if(String(failure.code).startsWith("SQLITE_CONSTRAINT"))throw error("FOCUS_TASK_DUPLICATE","任务已经关联");throw failure;}return get(account,goalId);}
 function detachTask(identityId,goalId,taskId){const account=owner(identityId);if(!get(account,goalId))throw error("FOCUS_NOT_FOUND","Focus not found");if(!db.prepare("DELETE FROM goal_work_items WHERE goal_id=? AND work_item_id=?").run(String(goalId),String(taskId)).changes)throw error("FOCUS_TASK_NOT_FOUND","Task link not found");return get(account,goalId);}
 return {list,create,update,remove,attachTask,detachTask,close:()=>db.close()};
}
